account/urls.py
from django.urls import path

from account.views import (ArticleList,
                           ArticleCreate,
                           ArticleUpdate,
                           ArticleDelete, Profile, Client_list, ClientCreate, ClientUpdate, ClientDelete,
                           Reference_List, ReferenceCreate, ReferenceUpdate, ReferenceDelete,
                           pie_chart,
                           )

app_name = "account"

urlpatterns = [path("", ArticleList.as_view(), name="home"),
               path('article/create', ArticleCreate.as_view(), name='article-create'),
               path('article/update/<int:pk>', ArticleUpdate.as_view(), name='article-update'),
               path('article/delete/<int:pk>', ArticleDelete.as_view(), name='article-delete'),
               path('profile/', Profile.as_view(), name='profile'),
               path("clientlist/", Client_list.as_view(), name="client_list"),
               path('client/create', ClientCreate.as_view(), name='client-create'),
               path('client/update/<int:pk>', ClientUpdate.as_view(), name='client-update'),
               path('client/delete/<int:pk>', ClientDelete.as_view(), name='client-delete'),
               path("referencelist/", Reference_List.as_view(), name="reference_list"),
               path('reference/create', ReferenceCreate.as_view(), name='reference-create'),
               path('reference/update/<int:pk>', ReferenceUpdate.as_view(), name='reference-update'),
               path('reference/delete/<int:pk>', ReferenceDelete.as_view(), name='reference-delete'),
               path('pie-chart/', pie_chart, name='pie_chart'),
               ]

blog/urls.py
from django.urls import path

from blog.views import (ArticleList,
                        ArticleDetailView,
                        CategoryList,
                        AuthorList, ArticlePreview)

app_name = "blog"
urlpatterns = [
    path('', ArticleList.as_view(), name="home"),
    path('page/<int:page>', ArticleList.as_view(), name="home"),
    path('article/<slug:slug>', ArticleDetailView.as_view(), name="detail"),
    path('article/preview/<int:pk>', ArticlePreview.as_view(), name="preview"),
    path('category/<slug:slug>', CategoryList.as_view(), name="category"),
    path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(), name="category"),
    path('author/<slug:username>', AuthorList.as_view(), name="author"),
    path('author/<slug:username>/page/<int:page>', AuthorList.as_view(), name="author")]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, re_path
from django.urls import path

from account.views import Login, Register, activate

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('comment/', include('comment.urls')),
                  path('', include("blog.urls")),
                  path('', include("django.contrib.auth.urls")),
                  path('login/', Login.as_view(), name='login'),
                  path('register/', Register.as_view(), name='register'),
                  path(
                      'activate/<slug:uidb64>/<slug:token>/',
                      activate,
                      name='activate'),
                  path('account/', include("account.urls")),
                  path('contact/', include("contact.urls")),
                  re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
                  path('todo/', include('todo.urls', namespace="todo")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.conf import settings
from django.urls import path

from todo import views
from todo.features import HAS_TASK_MERGE

app_name = "todo"

urlpatterns = [
    path("", views.list_lists, name="lists"),
    # View reorder_tasks is only called by JQuery for drag/drop task ordering.
    path("reorder_tasks/", views.reorder_tasks, name="reorder_tasks"),
    # Allow users to post tasks from outside django-todo (e.g. for filing tickets - see docs)
    path("ticket/add/", views.external_add, name="external_add"),
    # Three paths into `list_detail` view
    path("mine/", views.list_detail, {"list_slug": "mine"}, name="mine"),
    path(
        "<int:list_id>/<str:list_slug>/completed/",
        views.list_detail,
        {"view_completed": True},
        name="list_detail_completed",
    ),
    path("<int:list_id>/<str:list_slug>/", views.list_detail, name="list_detail"),
    path("<int:list_id>/<str:list_slug>/delete/", views.del_list, name="del_list"),
    path("add_list/", views.add_list, name="add_list"),
    path("task/<int:task_id>/", views.task_detail, name="task_detail"),
    path(
        "attachment/remove/<int:attachment_id>/", views.remove_attachment, name="remove_attachment"
    ),
]

if HAS_TASK_MERGE:
    # ensure mail tracker autocomplete is optional
    from todo.views.task_autocomplete import TaskAutocomplete

    urlpatterns.append(
        path(
            "task/<int:task_id>/autocomplete/", TaskAutocomplete.as_view(), name="task_autocomplete"
        )
    )

urlpatterns.extend(
    [
        path("toggle_done/<int:task_id>/", views.toggle_done, name="task_toggle_done"),
        path("delete/<int:task_id>/", views.delete_task, name="delete_task"),
        path("search/", views.search, name="search"),
        path("import_csv/", views.import_csv, name="import_csv"),
    ]
)

comment/views/base.py
from django.views.generic import FormView

from comment.conf import settings
from comment.context import DABContext
from comment.responses import DABResponseData
from comment.messages import EmailInfo
from comment.service.email import DABEmailService
from comment.forms import CommentForm


class BaseCommentView(FormView, DABResponseData):
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = context.pop('form')
        context.update(DABContext(self.request))
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class CommentCreateMixin(BaseCommentView):
    email_service = None

    def _initialize_email_service(self, comment, request):
        self.email_service = DABEmailService(comment, request)

    def _send_notification_to_followers(self, comment, request):
        if settings.COMMENT_ALLOW_SUBSCRIPTION:
            self._initialize_email_service(comment, request)
            self.email_service.send_notification_to_followers()

    def perform_save(self, comment, request):
        comment.save()
        self._send_notification_to_followers(comment, request)
        comment.refresh_from_db()
        return comment

    def _handle_anonymous(self, comment, request, api=False):
        self._initialize_email_service(comment, request)
        self.email_service.send_confirmation_request(api=api)
        self.anonymous = True
        self.msg = EmailInfo.CONFIRMATION_SENT

    def perform_create(self, comment, request, api=False):
        if settings.COMMENT_ALLOW_ANONYMOUS and not comment.user:
            self._handle_anonymous(comment, request, api)
        else:
            comment = self.perform_save(comment, request)
        return comment

todo/views/add_list.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.exceptions import PermissionDenied
from django.db import IntegrityError
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.utils.text import slugify

from todo.forms import AddTaskListForm
from todo.utils import staff_check


@login_required
@user_passes_test(staff_check)
def add_list(request) -> HttpResponse:
    """Allow users to add a new todo list to the group they're in.
    """

    # Only staffers can add lists, regardless of TODO_STAFF_USER setting.
    if not request.user.is_staff:
        raise PermissionDenied

    if request.POST:
        form = AddTaskListForm(request.user, request.POST)
        if form.is_valid():
            try:
                newlist = form.save(commit=False)
                newlist.slug = slugify(newlist.name)
                newlist.save()
                messages.success(request, "یک لیست جدید اضافه شد.")
                return redirect("todo:lists")

            except IntegrityError:
                messages.warning(
                    request,
                    "یک مشکل در ذخیره کردن لیست جدید بوجود آمد. "
                    "به احتمال زیاد یک لیست با همان نام در همان گروه در حال حاضر وجود دارد.",
                )
    else:
        if request.user.groups.all().count() == 1:
            # FIXME: Assuming first of user's groups here; better to prompt for group
            form = AddTaskListForm(request.user, initial={"group": request.user.groups.all()[0]})
        else:
            form = AddTaskListForm(request.user)

    context = {"form": form}

    return render(request, "todo/add_list.html", context)

todo/views/del_list.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from todo.models import Task, TaskList
from todo.utils import staff_check


@login_required
@user_passes_test(staff_check)
def del_list(request, list_id: int, list_slug: str) -> HttpResponse:
    """Delete an entire list. Only staff members should be allowed to access this view.
    """
    task_list = get_object_or_404(TaskList, id=list_id)

    # Ensure user has permission to delete list. Get the group this list belongs to,
    # and check whether current user is a member of that group AND a staffer.
    if task_list.group not in request.user.groups.all():
        raise PermissionDenied    
    if not request.user.is_staff:
        raise PermissionDenied

    if request.method == "POST":
        TaskList.objects.get(id=task_list.id).delete()
        messages.success(request, "لیست {list_name} پاک شد.".format(list_name=task_list.name))
        return redirect("todo:lists")
    else:
        task_count_done = Task.objects.filter(task_list=task_list.id, completed=True).count()
        task_count_undone = Task.objects.filter(task_list=task_list.id, completed=False).count()
        task_count_total = Task.objects.filter(task_list=task_list.id).count()

    context = {
        "task_list": task_list,
        "task_count_done": task_count_done,
        "task_count_undone": task_count_undone,
        "task_count_total": task_count_total,
    }

    return render(request, "todo/del_list.html", context)

todo/views/delete_task.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse

from todo.models import Task
from todo.utils import staff_check


@login_required
@user_passes_test(staff_check)
def delete_task(request, task_id: int) -> HttpResponse:
    """Delete specified task.
    Redirect to the list from which the task came.
    """

    if request.method == "POST":
        task = get_object_or_404(Task, pk=task_id)

        redir_url = reverse(
            "todo:list_detail",
            kwargs={"list_id": task.task_list.id, "list_slug": task.task_list.slug},
        )

        # Permissions
        if not (
            (task.created_by == request.user)
            or (request.user.is_superuser)
            or (task.assigned_to == request.user)
            or (task.task_list.group in request.user.groups.all())
        ):
            raise PermissionDenied

        task.delete()

        messages.success(request, "کار '{}' پاک شد.".format(task.title))
        return redirect(redir_url)

    else:
        raise PermissionDenied

todo/views/external_add.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import get_user_model
from django.contrib.sites.models import Site
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string

from todo.defaults import defaults
from todo.forms import AddExternalTaskForm
from todo.models import TaskList
from todo.utils import staff_check


@login_required
@user_passes_test(staff_check)
def external_add(request) -> HttpResponse:
    """Allow authenticated users who don't have access to the rest of the ticket system to file a ticket
    in the list specified in settings (e.g. django-todo can be used a ticket filing system for a school, where
    students can file tickets without access to the rest of the todo system).

    Publicly filed tickets are unassigned unless settings.DEFAULT_ASSIGNEE exists.
    """

    if not settings.TODO_DEFAULT_LIST_SLUG:
        # We do NOT provide a default in defaults
        raise RuntimeError(
            "This feature requires TODO_DEFAULT_LIST_SLUG: in settings. See documentation."
        )

    if not TaskList.objects.filter(slug=settings.TODO_DEFAULT_LIST_SLUG).exists():
        raise RuntimeError(
            "There is no TaskList with slug specified for TODO_DEFAULT_LIST_SLUG in settings."
        )

    if request.POST:
        form = AddExternalTaskForm(request.POST)

        if form.is_valid():
            current_site = Site.objects.get_current()
            task = form.save(commit=False)
            task.task_list = TaskList.objects.get(slug=settings.TODO_DEFAULT_LIST_SLUG)
            task.created_by = request.user
            if defaults("TODO_DEFAULT_ASSIGNEE"):
                task.assigned_to = get_user_model().objects.get(username=settings.TODO_DEFAULT_ASSIGNEE)
            task.save()

            # Send email to assignee if we have one
            if task.assigned_to:
                email_subject = render_to_string(
                    "todo/email/assigned_subject.txt", {"task": task.title}
                )
                email_body = render_to_string(
                    "todo/email/assigned_body.txt", {"task": task, "site": current_site}
                )
                try:
                    send_mail(
                        email_subject,
                        email_body,
                        task.created_by.email,
                        [task.assigned_to.email],
                        fail_silently=False,
                    )
                except ConnectionRefusedError:
                    messages.warning(
                        request, "کار ایجا شد. ولی ایمیل نشد لظفا با مدیریت تماس بگیرید.."
                    )

            messages.success(
                request, "مشکل شما دریافت شد . به زودی به آن پاسخ خواهیم داد."
            )
            return redirect(defaults("TODO_PUBLIC_SUBMIT_REDIRECT"))

    else:
        form = AddExternalTaskForm(initial={"priority": 999})

    context = {"form": form}

    return render(request, "todo/add_task_external.html", context)

todo/views/import_csv.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse
from django.shortcuts import redirect, render, reverse

from todo.operations.csv_importer import CSVImporter
from todo.utils import staff_check


@login_required
@user_passes_test(staff_check)
def import_csv(request) -> HttpResponse:
    """Import a specifically formatted CSV into stored tasks.
    """

    ctx = {"results": None}

    if request.method == "POST":
        filepath = request.FILES.get("csvfile")

        if not filepath:
            messages.error(request, "شما باید یک فایل CSV را وارد کنید.")
            return redirect(reverse("todo:import_csv"))

        importer = CSVImporter()
        results = importer.upsert(filepath)

        if results:
            ctx["results"] = results
        else:
            messages.error(request, "فایل ارسال قابلیت تفکیک شدن ندارد.")
            return redirect(reverse("todo:import_csv"))

    return render(request, "todo/import_csv.html", context=ctx)

todo/views/remove_attachment.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse

from todo.models import Attachment
from todo.utils import remove_attachment_file


@login_required
def remove_attachment(request, attachment_id: int) -> HttpResponse:
    """Delete a previously posted attachment object and its corresponding file
    from the filesystem, permissions allowing.
    """

    if request.method == "POST":
        attachment = get_object_or_404(Attachment, pk=attachment_id)

        redir_url = reverse("todo:task_detail", kwargs={"task_id": attachment.task.id})

        # Permissions
        if not (
            attachment.task.task_list.group in request.user.groups.all()
            or request.user.is_superuser
        ):
            raise PermissionDenied

        if remove_attachment_file(attachment.id):
            messages.success(request, f" ضمیمه  {attachment.id} پاک شد..")
        else:
            messages.error(
                request, f"متاسفم, مشکلی در پاک کردن ضمیمه وجود دارد . {attachment.id}."
            )

        return redirect(redir_url)

    else:
        raise PermissionDenied

todo/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <title>{% block title_meta %} عنوان صفحه {% endblock %}</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <!-- Font Awesome -->
    <link href="{% static 'registration/adminlte/plugins/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
    <!-- Ionicons -->
    <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link href="{% static 'registration/adminlte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}"
          rel="stylesheet">
    <!-- iCheck -->
    <link href="{% static 'registration/adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}"
          rel="stylesheet">
    <!-- JQVMap -->
    <link href="{% static 'registration/adminlte/plugins/jqvmap/jqvmap.min.css' %}" rel="stylesheet">
    <!-- Theme style -->
    <link href="{% static 'registration/adminlte/assets/css/adminlte.min.css' %}" rel="stylesheet">
    <!-- overlayScrollbars -->
    <link href="{% static 'registration/adminlte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}"
          rel="stylesheet">
    <!-- Daterange picker -->
    <link href="{% static 'registration/adminlte/plugins/daterangepicker/daterangepicker.css' %}" rel="stylesheet">
    <!-- summernote -->
    <link href="{% static 'registration/adminlte/plugins/summernote/summernote-bs4.css' %}" rel="stylesheet">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- Bootstrap 4 RTL -->
    <link href="https://cdn.rtlcss.com/bootstrap/v4.2.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom style for RTL -->
    <link href="{% static 'registration/adminlte/assets/css/custom.css' %}" rel="stylesheet">
    <link href="/static/css/sticky-footer-navbar.css" rel="stylesheet">
    {% block extrahead %}{% endblock extrahead %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a class="nav-link" href="{% url 'account:home' %}">صفحه اصلی</a>
            </li>

            {% if user.is_authenticated %}
            <li class="nav-item d-none d-sm-inline-block">
                <a class="nav-link" href="{% url 'todo:lists' %}">لیست انجام کار</a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a class="nav-link" href="{% url 'todo:mine' %}">کارها</a>
            </li>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a class="nav-link" href="{% url 'todo:import_csv' %}">وارد کرد اطلاعات</a>
            </li>
            {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">ورود</a></li>
            {% endif %}
            <li class="nav-item d-none d-sm-inline-block">
                <a class="nav-link" href="{% url 'blog:home' %}" target="_blank">نمایش سایت</a>
            </li>
            {% if user.is_authenticated %}
            <form action="{% url 'todo:search' %}" aria-label="Search" class="form-inline mt-2 mt-md-0"
                  method="get" placeholder="جستجو">
                <input class="form-control mr-sm-2" id="q" name="q" type="text" value="">
                <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="جستجو در بین کارها">
            </form>
            {% endif %}
        </ul>
        <ul class="navbar-nav mr-auto-navbav">
            <!-- Messages Dropdown Menu -->
            <li class="nav-item">
                <a class="nav-link" data-slide="true" data-widget="control-sidebar" href="{% url 'logout' %}">
                    <i class="fas fa-sign-out-alt"></i>
                </a>
            </li>
        </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    {% include 'registration/sidebar.html' %}
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                {% if messages %}
                {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}

                <p>{{ form.non_field_errors }}</p>
                {% block main%}{% block content %}
                {% endblock %}{% endblock %}
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
        <span>شرکت هویار ترابر  ثبت 1389</span>

        <div class="float-right d-none d-sm-inline-block">
            <b>Version</b> 3.0.0-rc.1
        </div>
        <span class="text-muted">
          django-todo, {% now "Y" %}.
          {% if user.is_authenticated %}Logged in as {{ user.username }}{% endif %}</span>
    </footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'registration/adminlte/plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'registration/adminlte/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button)

</script>
<!-- Bootstrap 4 rtl -->
<script src="https://cdn.rtlcss.com/bootstrap/v4.2.1/js/bootstrap.min.js"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'registration/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'registration/adminlte/plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'registration/adminlte/plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'registration/adminlte/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'registration/adminlte/plugins/jqvmap/maps/jquery.vmap.world.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'registration/adminlte/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'registration/adminlte/plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'registration/adminlte/plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'registration/adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static 'registration/adminlte/plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'registration/adminlte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'registration/adminlte/assets/js/adminlte.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'registration/adminlte/assets/js/pages/dashboard.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'registration/adminlte/assets/js/demo.js' %}"></script>
{% block extra_js %}{% endblock extra_js %}
</body>
</html>