blog/urls.py
from django.urls import path

from blog.views import (ArticleList,
                        ArticleDetailView,
                        CategoryList,
                        AuthorList, ArticlePreview)

app_name = "blog"
urlpatterns = [
    path('', ArticleList.as_view(), name="home"),
    path('page/<int:page>', ArticleList.as_view(), name="home"),
    path('article/<slug:slug>', ArticleDetailView.as_view(), name="detail"),
    path('article/preview/<int:pk>', ArticlePreview.as_view(), name="preview"),
    path('category/<slug:slug>', CategoryList.as_view(), name="category"),
    path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(), name="category"),
    path('author/<slug:username>', AuthorList.as_view(), name="author"),
    path('author/<slug:username>/page/<int:page>', AuthorList.as_view(), name="author")]

contact/urls.py
from django.urls import path

from contact.views import ContactList, ContactProfileDetailView, ContactListView, ContactCreate, ContactUpdate, \
    ContactDetailCreate, ContactDetailUpdate, ContactDelete

app_name = "contact"

urlpatterns = [path("contactlist/", ContactList.as_view(), name="contact_list"),
               path('detail/<slug:slug>', ContactListView.as_view(), name="contact_detail"),
               path('detail/profile/<int:pk>', ContactProfileDetailView.as_view(),
                    name="contact_detail_profile"),
               path('create/company', ContactCreate.as_view(), name='contact-create'),
               path('update/company/<int:pk>', ContactUpdate.as_view(), name='contact_update'),
               path('create/contact_detail', ContactDetailCreate.as_view(), name='contact_detail_create'),
               path('update/contact_detail/<int:pk>', ContactDetailUpdate.as_view(), name='contact_detail_update'),
               path('contact_detail/delete/<int:pk>', ContactDelete.as_view(), name='contact_delete'),
               ]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, re_path
from django.urls import path

from account.views import Login, Register, activate

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('comment/', include('comment.urls')),
                  path('', include("blog.urls")),
                  path('', include("django.contrib.auth.urls")),
                  path('login/', Login.as_view(), name='login'),
                  path('register/', Register.as_view(), name='register'),
                  path(
                      'activate/<slug:uidb64>/<slug:token>/',
                      activate,
                      name='activate'),
                  path('account/', include("account.urls")),
                  path('contact/', include("contact.urls")),
                  re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
                  path('todo/', include('todo.urls', namespace="todo")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.html import format_html

from account.models import User
from comment.models import Comment
from extensions.utils import Jalali_covertor


class ArticleManager(models.Manager):
    def publish(self):
        return self.filter(status='p')


class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)


class Category(models.Model):
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, default=None, null=True, blank=True,
                               related_name='children', verbose_name="عبارت زیر دسته")
    title = models.CharField(verbose_name="عنوان دسته بندی", max_length=200)
    slug = models.SlugField(verbose_name="آدرس دسته بندی", max_length=100, unique=True)
    status = models.BooleanField(verbose_name="آیا نمایش داده شود؟", default=True)
    position = models.IntegerField(verbose_name="پوزیشن")

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"
        ordering = ["parent__id", "position"]

    def __str__(self):
        return self.title

    objects = CategoryManager()


class Article(models.Model):
    STATUS_CHOICES = (('d', 'پیش نویس'),  # draft
                      ('p', 'منتشر شده'),  # publish
                      ('i', 'در حال بررسی'),  # investigation
                      ('b', 'برگشت داده شده'),)  # back
    title = models.CharField(verbose_name="موضوع", max_length=200)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name="articles",
                               verbose_name="نویسنده")
    is_special = models.BooleanField(default=False, verbose_name="مقاله ویژه")
    slug = models.SlugField(verbose_name="آدرس مقاله", max_length=100, unique=True)
    description = models.TextField(verbose_name="توضیحات", )
    thumbnail = models.ImageField(verbose_name="عکس بند انگشتی", upload_to="images")
    publish = models.DateTimeField(verbose_name="زمان ایجاد", default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(verbose_name="وضعیت", max_length=1, choices=STATUS_CHOICES)
    category = models.ManyToManyField(Category, verbose_name="دسته بندی", related_name="articles")
    comments = GenericRelation(Comment)

    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"
        ordering = ["-publish"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("account:home")

    def Jpublish(self):
        return Jalali_covertor(self.publish)

    Jpublish.short_description = "زمان انتشار"

    def category_publish(self):
        return self.category.filter(status=True)

    def thumbnail_tags(self):
        return format_html("<img width=80 height=60 style='border-radius: 5px' src='{}'>".format(self.thumbnail.url))

    thumbnail_tags.short_description = "عکس بند انگشتی"
    objects = ArticleManager()

    def category_to_str(self):
        return ",".join([category.title for category in self.category_publish()])

    category_to_str.short_description = "دسته بندی"

contact/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField
from shortuuidfield import ShortUUIDField
from taggit.managers import TaggableManager

from account.models import User
from comment.models import Comment
from extensions.utils import Jalali_covertor


class Contact(models.Model):
    uuid = ShortUUIDField(verbose_name="کد اختصاصی", unique=True)
    slug = models.SlugField(verbose_name="اسلاگ شرکت", max_length=100, unique=True)
    company_name = models.CharField(verbose_name="نام شرکت", max_length=30)
    creator = models.ForeignKey(User, verbose_name="ایجاد کننده", null=True, on_delete=models.CASCADE,
                                limit_choices_to={'is_active': True})
    created_on = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = "شرکت حمل "
        verbose_name_plural = "شرکت های حمل"

    def __str__(self):
        return self.company_name

    def get_absolute_url(self):
        return reverse("contact:contact_list")

    def Jpublish(self):
        return Jalali_covertor(self.created_on)

    Jpublish.short_description = "آخرین تماس با مشتری"


class DetailContact(models.Model):
    PHONE_NUMBER_TYPE_CHOICES = (
        ('home', 'Home'),
        ('mobile', 'Mobile'),
        ('fax', 'Fax'),
        ('work', 'Work'),
        ('other', 'Other')
    )
    EMAIL_TYPE_CHOICES = (
        ('private', 'private'),
        ('work', 'Work'),
        ('other', 'Other')
    )
    SHIPMENT_CHOICES = (('TT', 'TT'),  # truck
                        ('CC', 'CC'),  # ocean
                        ('AA', 'AA'),  # air
                        ('TR', 'TR'),)  # transit
    first_name = models.CharField(null=True, max_length=30, verbose_name="نام")
    last_name = models.CharField(max_length=30, verbose_name="نام خانوادگی")
    phone_type = models.CharField(max_length=10, choices=PHONE_NUMBER_TYPE_CHOICES, verbose_name="نوع شماره تماس")
    phone_number = PhoneNumberField(max_length=50, verbose_name="شماره تفن")
    email_type = models.CharField(max_length=10, choices=EMAIL_TYPE_CHOICES, verbose_name="نوع ایمیل")
    email_address = models.EmailField(max_length=255, db_index=True, verbose_name="آدرس ایمیل")
    contact_object = models.ForeignKey(Contact, verbose_name="شرکت در حال فعالت", null=True,
                                       related_name='contact_phone_number',
                                       on_delete=models.CASCADE)
    author = models.ForeignKey(User, null=True,
                               related_name='creator_contact',
                               on_delete=models.CASCADE, verbose_name="ایجاد کننده")
    kind_shipment = models.CharField(verbose_name="حیطه فعالیت", max_length=2, choices=SHIPMENT_CHOICES)
    tags = TaggableManager()
    is_active = models.BooleanField(default=True, verbose_name="آیا این شخص  فغال می باشد ؟")
    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    comments = GenericRelation(Comment)

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)

    class Meta:
        db_table = 'contacts_detail'
        verbose_name = "اطلاعات تماس با شرکت های حمل "
        verbose_name_plural = "اطلاعات تماس  با شرکت های حمل"
        ordering = ["-is_active", "date_modified"]

    def get_absolute_url(self):
        return reverse("contact:contact_list")

blog/views.py
from django.shortcuts import get_object_or_404
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from account.mixin import AuthorAccessMixin
from account.models import User
from blog.models import Article, Category


# object Base view
# def home(request, page=1):
#     articles_list = Article.objects.publish()
#     p = Paginator(articles_list, 4)
#     articles = p.get_page(page)
#     context = {
#         "articles": articles
#     }
#     return render(request, "blog/home.html", context)


# class Base view
class ArticleList(ListView):
    # model = Article
    template_name = "blog/home.html"
    context_object_name = "articles"
    queryset = Article.objects.publish()
    paginate_by = 3


# object Base view
# def detail(request, slug):
#     context = {
#         "article": get_object_or_404(Article.objects.publish(), slug=slug, status="p")
#
#     }
#     return render(request, "blog/detail.html", context)


# class Base view
class ArticleDetailView(DetailView):
    def get_object(self):
        slug = self.kwargs.get("slug")
        return get_object_or_404(Article.objects.publish(), slug=slug)

    template_name = "blog/detail.html"


class ArticlePreview(AuthorAccessMixin, DetailView):
    def get_object(self):
        pk = self.kwargs.get("pk")
        return get_object_or_404(Article, pk=pk)

    template_name = "blog/detail.html"


# def category(request, slug, page=1):
#     category = get_object_or_404(Category, slug=slug, status=True)
#     articles_list = category.articles.publish()
#     p = Paginator(articles_list, 3)
#     articles = p.get_page(page)
#     context = {
#         "category": category,
#         "articles": articles
#
#     }
#     return render(request, "blog/category.html", context)

class CategoryList(ListView):
    template_name = "blog/category.html"
    context_object_name = "articles"
    paginate_by = 4

    def get_queryset(self):
        global category
        slug = self.kwargs.get("slug")
        category = get_object_or_404(Category.objects.active(), slug=slug)
        return category.articles.publish()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context


class AuthorList(ListView):
    template_name = "blog/author_list.html"
    paginate_by = 4
    context_object_name = "articles"

    def get_queryset(self):
        global author
        username = self.kwargs.get("username")
        author = get_object_or_404(User, username=username)
        return author.articles.publish()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = author
        return context

comment/views/base.py
from django.views.generic import FormView

from comment.conf import settings
from comment.context import DABContext
from comment.responses import DABResponseData
from comment.messages import EmailInfo
from comment.service.email import DABEmailService
from comment.forms import CommentForm


class BaseCommentView(FormView, DABResponseData):
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = context.pop('form')
        context.update(DABContext(self.request))
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class CommentCreateMixin(BaseCommentView):
    email_service = None

    def _initialize_email_service(self, comment, request):
        self.email_service = DABEmailService(comment, request)

    def _send_notification_to_followers(self, comment, request):
        if settings.COMMENT_ALLOW_SUBSCRIPTION:
            self._initialize_email_service(comment, request)
            self.email_service.send_notification_to_followers()

    def perform_save(self, comment, request):
        comment.save()
        self._send_notification_to_followers(comment, request)
        comment.refresh_from_db()
        return comment

    def _handle_anonymous(self, comment, request, api=False):
        self._initialize_email_service(comment, request)
        self.email_service.send_confirmation_request(api=api)
        self.anonymous = True
        self.msg = EmailInfo.CONFIRMATION_SENT

    def perform_create(self, comment, request, api=False):
        if settings.COMMENT_ALLOW_ANONYMOUS and not comment.user:
            self._handle_anonymous(comment, request, api)
        else:
            comment = self.perform_save(comment, request)
        return comment

contact/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DeleteView, CreateView, UpdateView

from account.mixin import AuthorLogin, FieldsContactMixin, FormContactValiMixin, FieldsContactDetailMixin, \
    FormContactDetailValiMixin, ContactDeleteAccessMixin
from contact.models import Contact, DetailContact


class ContactList(AuthorLogin, LoginRequiredMixin, ListView):
    template_name = "registration/contact_list.html"
    context_object_name = "contacts"
    queryset = Contact.objects.all()


class ContactCreate(AuthorLogin, LoginRequiredMixin, FieldsContactMixin, FormContactValiMixin, CreateView):
    model = Contact
    template_name = "registration/contact-create-update.html"


#
class ContactUpdate(LoginRequiredMixin, FieldsContactMixin, FormContactValiMixin, UpdateView):
    model = Contact
    template_name = "registration/contact-create-update.html"


# contactlist


class ContactListView(AuthorLogin, LoginRequiredMixin, ListView):
    def get_queryset(self):
        slug = self.kwargs.get("slug")
        detail_contacts = DetailContact.objects.filter(contact_object__slug=slug)
        return detail_contacts

    template_name = "registration/contact_detail.html"


class ContactProfileDetailView(AuthorLogin, LoginRequiredMixin, DeleteView):
    context_object_name = "contact"

    def get_object(self):
        pk = self.kwargs.get("pk")
        return get_object_or_404(DetailContact, pk=pk)

    template_name = "registration/contact_detail_profile.html"


class ContactDetailCreate(AuthorLogin, LoginRequiredMixin, FieldsContactDetailMixin, FormContactDetailValiMixin,
                          CreateView):
    model = DetailContact
    template_name = "registration/contact-detail-create-update.html"


class ContactDetailUpdate(AuthorLogin, LoginRequiredMixin, FieldsContactDetailMixin, FormContactDetailValiMixin,
                          UpdateView):
    model = DetailContact
    template_name = "registration/contact-detail-create-update.html"


class ContactDelete(ContactDeleteAccessMixin, DeleteView):
    model = DetailContact
    success_url = reverse_lazy('contact:contact_list')
    template_name = "registration/contact-confirm-delete.html"

templates/blog/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

templates/blog/author_list.html
{% extends 'blog/list.html' %}

{% block header %}
<h3 class="alert alert-primary text-center font-family: 'Sahel'">نویسنده :{{author.get_full_name}}</h3>
{% endblock%}

{% block previous_obj_url%}
{% url 'blog:author' author.username page_obj.previous_page_number%}
{%endblock%}

{% block next_obj_url%}
{% url 'blog:author' author.username page_obj.next_page_number %}
{%endblock%}

templates/blog/base.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport"/>
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    <title>{% block title%}{% endblock%}</title>
    <link href="{% static 'blog/assets/favicon.ico' %}" rel="icon" type="image/x-icon"/>
    <!-- Font Awesome icons (free version)-->
    <script crossorigin="anonymous" src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet"
          type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
          rel="stylesheet" type="text/css"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'blog/css/styles.css'%}" rel="stylesheet"/>
    <link href="{% static 'blog/css/rtl.css'%}" rel="stylesheet"/>

    <link href="{% static 'star-ratings/css/star-ratings.css' %}" rel="stylesheet">
    <script src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}" type="text/javascript"></script>
</head>
<body>
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'blog:home'%}">{% title %}</a>
        <button aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"
                class="navbar-toggler"
                data-bs-target="#navbarResponsive" data-bs-toggle="collapse" type="button">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        {% category_navbar %}
    </div>
</nav>
{% block main %}
{% endblock %}
<!-- Footer-->
<footer class="border-top">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                        </a>
                    </li>
                </ul>
                <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
            </div>
        </div>
    </div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'blog/js/scripts.js' %}"></script>
</body>
</html>

templates/blog/category.html
{% extends 'blog/list.html' %}

{% block header %}
<h3 class="alert alert-primary text-center font-family: 'Sahel'">دسته بندی :{{category.title}}</h3>
{% endblock%}

{% block previous_obj_url%}
    {% url 'blog:category' category.slug page_obj.previous_page_number%}
{%endblock%}

{% block next_obj_url%}
    {% url 'blog:category' category.slug page_obj.next_page_number %}
{%endblock%}

templates/blog/home.html
{% extends 'blog/list.html' %}

{% block header %}
{% endblock%}

{% block previous_obj_url%}
{% url 'blog:home'  page_obj.previous_page_number%}
{%endblock%}

{% block next_obj_url%}
{% url 'blog:home'  page_obj.next_page_number %}
{%endblock%}

templates/blog/list.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title%}هویار ترابر{% endblock %}
{% block main%}
{% load ratings %}
<!-- Page Header-->
<header class="masthead" style="background-image: url('{% static 'blog/assets/img/home-bg.jpg' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>هویار ترابر</h1>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            {% block header %}
            <h3 class="alert alert-primary text-center font-family: 'Sahel'">دسته بندی :{{category.title}}</h3>
            {% endblock%}
            <!-- Post preview-->
            {% for article in articles %}
            <div class="post-preview">
                <a href="{% url 'blog:detail' article.slug%}">
                    <h2 class="post-title">

                        {{article.title}}


                        {% if article.is_special %}
                        <span class="badge btn-danger" style="font-size: 14px;">ویژه</span>
                        {% endif %}
                    </h2>
                </a>
                <div>{% ratings article %}</div>


                <p class="post-subtitle">{{article.description |striptags|truncatewords:30}}</p>

                <p class="post-meta">
                    نوشته شده توسط:
                    <a href="{% url 'blog:author' article.author%}">{{article.author.get_full_name}}</a>
                    {{article.Jpublish}}
                </p>
                <div>
                    {% for cat in article.category.active%}
                    <a href="{% url 'blog:category' cat.slug%}">#{{cat.title}}</a>
                    {%endfor%}
                </div>
            </div>
            {% endfor %}
            <!-- Divider-->
            <hr class="my-4 pager_button"/>
            <!-- Pager-->
            {% if is_paginated %}
            <div class="d-flex justify-content-end mb-4">
                {% if page_obj.has_previous %}
                <a class="btn btn-primary text-uppercase"
                   href="{% block previous_obj_url%} {%endblock%}"> پست
                    های جدید&rarr;</a>
                {% endif %}
                {% if page_obj.has_next %}
                <a class="btn btn-primary text-uppercase"
                   href="{% block next_obj_url%} {%endblock%}"> پست
                    های قدیمی&larr;</a>
                {% endif %}
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}